name: Run PHPUnit with Sail

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip php-cli php-mbstring git
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install

      - name: Copy .env and generate app key
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d
          sleep 15
          ./vendor/bin/sail artisan key:generate

      - name: Run tests
        run: ./vendor/bin/sail test
